### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by khaledkbadr** [khaledkbadr/rasket#2]
A document to track the directions to the MVP

**gRPC Server:**

- [ ] handling multiple applications [feature] (#3) 
- [ ] rocksdb as a storage [feature] (#4)
- [ ] retrieval filters [feature] (#5)
- [ ] storing incoming data (#7)

**gRPC Client**

- [ ] Buffer layer (#6)
